# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19fb945b347e5cf96904172bace09a325fb862695db79ad6ff257cfcd5604919c25bab72a2995b46be7fe52e6d950c7a62ca7c0b6208038a0a113fef23a28259

test:
  secret_key_base: 218158acb550c88341dcb52a43b70b405066da0a85153a551df072728b53916814bbd4d6fb36e2ba87983f53734eb7b78bc69172924bb3adca0ddd5f28199c4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
